### ISSUE TITLE
encoding error when installing

### ISSUE THREAD

**Issue by inetbusiness** [mikel/tmail#16]
full message:
`.rvm/gems/ruby-2.4.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'tmail'.
Gem Load Error is: /.../n has a non escaped non ASCII character in non ASCII-8BIT script
Backtrace for gem load error is:
.rvm/gems/ruby-2.4.1/gems/tmail-1.2.7.1/lib/tmail/utils.rb:117:in `<module:TextUtils>'`

**Comment by ostaptan** [comment]
the same thing for ruby 2.5.7
